{
 "title": "Backend API + DB Monitoring",
 "tags": [
  "backend",
  "php",
  "mariadb"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Requests Total",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "requests" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 16, "h": 6 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])" }
   ]
  },
  {
   "title": "DB Queries Total",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 8, "h": 6 },
   "targets": [
    { "expr": "db_queries_total", "legendFormat": "queries" }
   ]
  },
  {
   "title": "MariaDB Active Connections",
   "type": "gauge",
   "gridPos": { "x": 8, "y": 6, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected"
    }
   ]
  },
  {
   "title": "Nginx Active Connections",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 6, "w": 8, "h": 6 },
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  }
 ]
}